FROM rust:1.88-slim-bookworm as builder

RUN apt-get update && \
    apt-get install -y \
      curl \
      libssl-dev \
      ca-certificates \
      build-essential \
      pkg-config \
      openssh-client && \
    rm -rf /tmp/* /var/{tmp,cache}/* /var/lib/{apt,dpkg}/

WORKDIR /app
COPY . .

# download public key for github.com
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh cargo build --release -p shielder-relayer

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y \
      libssl-dev \
      tini \
      ca-certificates && \
      rm -rf /tmp/* /var/{tmp,cache}/* /var/lib/{apt,dpkg}/

COPY --from=builder /app/target/release/shielder-relayer /usr/local/bin
RUN chmod +x /usr/local/bin/shielder-relayer

RUN useradd server
USER server

ENTRYPOINT ["tini", "--", "shielder-relayer"]
