---
name: 'Get Workflow Run ID'
description: 'Gets workflow run ID for a successful workflow run by workflow name and commit SHA'
inputs:
  workflow-name:
    description: 'The workflow file name (e.g., on-push-main.yml)'
    required: true
  full-sha:
    description: 'The full commit SHA'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true
outputs:
  workflow-run-id:
    description: 'The workflow run ID'
    value: ${{ steps.get-run-id.outputs.workflow-run-id }}
runs:
  using: "composite"
  steps:
    - name: Get workflow run ID and verify completion
      id: get-run-id
      shell: bash
      # yamllint disable rule:line-length
      run: |
        echo "Getting workflow run for SHA ${{ inputs.full-sha }} and workflow ${{ inputs.workflow-name }}"

        # Get all workflow runs for the SHA and filter for successful ones
        SUCCESSFUL_RUNS=$(curl -s -H "Authorization: Bearer ${{ inputs.github_token }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ inputs.workflow-name }}/runs" \
          | jq '.workflow_runs[] | select(.head_sha=="${{ inputs.full-sha }}" and .status=="completed" and .conclusion=="success") | {id, status, conclusion, created_at}')

        if [[ -z "$SUCCESSFUL_RUNS" || "$SUCCESSFUL_RUNS" == "null" ]]; then
          echo "Error: No successful workflow run found for SHA ${{ inputs.full-sha }} and workflow ${{ inputs.workflow-name }}"
          exit 1
        fi

        echo "Found successful workflow runs:"
        echo "$SUCCESSFUL_RUNS"

        # Get the newest run by sorting by created_at timestamp
        WORKFLOW_RUN_INFO=$(echo "$SUCCESSFUL_RUNS" | jq -s 'sort_by(.created_at) | reverse | .[0]')

        if [[ -z "$WORKFLOW_RUN_INFO" || "$WORKFLOW_RUN_INFO" == "null" ]]; then
          echo "Error: Failed to select the newest workflow run"
          exit 1
        fi

        echo "Selected newest workflow run: $WORKFLOW_RUN_INFO"

        # Extract run details
        STATUS=$(echo "$WORKFLOW_RUN_INFO" | jq -r '.status')
        CONCLUSION=$(echo "$WORKFLOW_RUN_INFO" | jq -r '.conclusion')
        RUN_ID=$(echo "$WORKFLOW_RUN_INFO" | jq -r '.id')
        CREATED_AT=$(echo "$WORKFLOW_RUN_INFO" | jq -r '.created_at')

        echo "Status: $STATUS"
        echo "Conclusion: $CONCLUSION"
        echo "Run ID: $RUN_ID"
        echo "Created at: $CREATED_AT"

        # Set output
        echo "workflow-run-id=$RUN_ID" >> $GITHUB_OUTPUT
