FROM rust:1.88-slim-bookworm AS builder

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .

RUN cargo build --release --features local-run -p shielder-scheduler-tee

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    ca-certificates \
    tini \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/shielder-scheduler-tee /usr/local/bin
RUN chmod +x /usr/local/bin/shielder-scheduler-tee

RUN useradd -r -s /bin/false server
USER server

ENTRYPOINT ["tini", "--", "shielder-scheduler-tee"]
