---
rust:
  directory: ../../crates/shielder_bindings

bindings:
  ts: src/gen/bindings

turboModule:
  ts: src/gen
  entrypoint: src/gen/index.tsx

ios:
  cargoExtras:
    - --features
    - build-uniffi
  frameworkName: build/RustFramework

android:
  useSharedLibrary: true
  cargoExtras:
    - --features
    - build-uniffi
