---
name: Build shielder-relayer Docker image

on:
  workflow_call:

jobs:
  build-shielder-relayer-image:
    name: Build shielder-relayer Docker image
    runs-on: github-large-runner-x64-8-cpu-32-gb-ram-300-gb-disk
    timeout-minutes: 10
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build shielder-relayer Docker image
        run: cd crates/shielder-relayer && make build-image

      - name: Save Docker image to tar
        run: docker save shielder-relayer:latest -o shielder-relayer-image.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: shielder-relayer-docker-image
          path: shielder-relayer-image.tar
          retention-days: 1
