---
name: Build wasm packages

on:
  workflow_call:
    inputs:
      target:
        description: 'Build target'
        required: true
        type: string
        default: 'wasm'
      artifact-name:
        description: 'Wasm artifact name'
        required: true
        type: string
        default: 'wasm-pkg'
      artifact-path:
        description: 'Path to wasm artifact'
        required: true
        type: string
        default: 'crates/shielder_bindings/pkg'
jobs:
  main:
    name: Build wasm packages
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build shielder_bindings
        run: cd crates/shielder_bindings && make ${{ inputs.target }}

      - name: Upload generated wasm to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 1

      - name: Upload generated proving keys to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: proving-keys-pkg
          path: crates/shielder_bindings/artifacts
          retention-days: 1
