---
name: Build and push fee-estimator.

on:
  workflow_call:
    inputs:
      ref:
        description: 'git ref: hash, branch, tag to build fee-estimator files from'
        type: string
        required: true

jobs:
  main:
    name: Build and push fee-estimator
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ECR_PUBLIC_HOST }}
          username: ${{ secrets.AWS_MAINNET_ECR_CC_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_MAINNET_ECR_CC_ACCESS_KEY }}

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v7

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env

      - name: Build fee-estimator
        run: cd crates/fee-estimator && cargo build --release

      - name: DOCKER | Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: DOCKER | Build and push latest docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./crates/fee-estimator/Dockerfile
          push: true
          # yamllint disable rule:line-length
          tags: |
             ${{ vars.ECR_CC_RES_PUBLIC_REGISTRY }}fee-estimator:${{ steps.get-ref-properties.outputs.sha }}
