---
name: Build and push ar-cli.

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git ref: hash, branch, tag to build ar-cli files from'
        type: string
        required: true

jobs:
  main:
    name: Build ar-cli.
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v7

      - name: Prepare Rust env
        uses: ./.github/actions/prepare-rust-env

      - name: Build ar-cli
        run: cd crates/ar-cli && cargo build --release

      - name: DOCKER | Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: DOCKER | Build and push latest docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./crates/ar-cli/Dockerfile
          push: true
          tags: |
             cardinalcryptography/ar-cli:${{ steps.get-ref-properties.outputs.sha }}
             cardinalcryptography/ar-cli:latest
