---
name: Push to main

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  build-and-push-fee-estimator:
    name: Build and push fee-estimator
    needs: [check-vars-and-secrets]
    secrets: inherit
    uses: ./.github/workflows/build-and-push-fee-estimator.yml
    with:
      ref: ${{ github.sha }}

  build-and-push-prover-server:
    name: Build and push shielder-prover-server
    needs: [check-vars-and-secrets]
    secrets: inherit
    uses: ./.github/workflows/build-and-push-prover-server.yml
    with:
      ref: ${{ github.sha }}

  build-and-push-scheduler-server:
    name: Build and push shielder-scheduler-server
    needs: [check-vars-and-secrets]
    secrets: inherit
    uses: ./.github/workflows/build-and-push-scheduler-server.yml
    with:
      ref: ${{ github.sha }}

  build-and-push-scheduler-tee:
    name: Build and push shielder-scheduler-tee
    needs: [check-vars-and-secrets]
    secrets: inherit
    uses: ./.github/workflows/build-and-push-scheduler-tee.yml
    with:
      ref: ${{ github.sha }}

  build-and-push-prover-tee:
    name: Build and push shielder-prover-tee
    needs: [check-vars-and-secrets]
    secrets: inherit
    uses: ./.github/workflows/build-and-push-prover-server.yml
    with:
      ref: ${{ github.sha }}

  get-short-sha:
    name: Get short SHA
    runs-on: ubuntu-22.04
    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - name: Calculate short SHA
        id: short-sha
        run: echo "sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT

  build-scheduler-tee-eif:
    name: Build shielder-scheduler-tee EIF (using dockerized nitro-cli)
    needs: [build-and-push-scheduler-tee, get-short-sha]
    uses: ./.github/workflows/_build-eif-from-docker.yml
    with:
      # yamllint disable-line rule:line-length
      public-docker-image-url: ${{ vars.ECR_CC_RES_PUBLIC_REGISTRY }}shielder-scheduler:tee-${{ needs.get-short-sha.outputs.short-sha }}
      component-name: shielder-scheduler-tee

  build-prover-tee-eif:
    name: Build shielder-prover-tee EIF (using dockerized nitro-cli)
    needs: [build-and-push-prover-tee, get-short-sha]
    uses: ./.github/workflows/_build-eif-from-docker.yml
    with:
      # yamllint disable-line rule:line-length
      public-docker-image-url: ${{ vars.ECR_CC_RES_PUBLIC_REGISTRY }}shielder-prover:${{ needs.get-short-sha.outputs.short-sha }}
      component-name: shielder-prover-tee
  all-jobs-completion:
    name: All jobs completion
    runs-on: ubuntu-24.04
    needs:
      - build-and-push-fee-estimator
      - build-and-push-prover-server
      - build-and-push-scheduler-server
      - build-and-push-scheduler-tee
      - build-and-push-prover-tee
      - get-short-sha
      - build-scheduler-tee-eif
      - build-prover-tee-eif
    if: >
      !cancelled() &&
      github.event_name != 'workflow_dispatch'
    steps:
      - name: Notify all jobs completed
        run: echo "All jobs have been completed successfully."

  slack-notification:
    name: Slack notification
    runs-on: ubuntu-24.04
    needs: [all-jobs-completion]
    if: >
      !cancelled() &&
      github.event_name != 'workflow_dispatch'
    steps:
      - name: Send Slack message
        uses: Cardinal-Cryptography/github-actions/slack-notification@v7
        with:
          notify-on: "failure"
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_BLANKSQUARE_NOTIFICATIONS }}
