---
name: PR commit

on:
  merge_group:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  build-enclave-artifacts:
    name: Build enclave artifacts
    uses: ./.github/workflows/_build-enclave-artifacts.yml
    with:
      ref: ${{ github.ref }}

  build-contracts:
    name: Generate and compile contracts
    needs: [check-vars-and-secrets]
    uses: ./.github/workflows/_build-contracts.yml
    secrets: inherit

  deploy-contracts:
    name: Deploy contracts
    needs: [build-contracts]
    uses: ./.github/workflows/_deploy-contracts.yml
    secrets: inherit

  rust-crates-checks:
    name: Rust crates checks
    needs: [build-contracts]
    uses: ./.github/workflows/_rust-crates-checks.yml
    secrets: inherit

  build-wasm-package:
    name: Build wasm package
    needs: [check-vars-and-secrets]
    uses: ./.github/workflows/_build-wasm-packages.yml
    secrets: inherit
    with:
      target: wasm
      artifact-name: wasm-pkg
      artifact-path: crates/shielder_bindings/pkg
      upload-proving-keys: true

  build-wasm-package-without-circuits:
    name: Build wasm package without circuits
    needs: [check-vars-and-secrets]
    uses: ./.github/workflows/_build-wasm-packages.yml
    secrets: inherit
    with:
      target: wasm-without-circuits
      artifact-name: wasm-pkg-without-circuits
      artifact-path: crates/shielder_bindings/pkg-without-circuits
      upload-proving-keys: false

  ts-checks:
    name: Typescript modules checks
    needs: [build-contracts, build-wasm-package, build-wasm-package-without-circuits]
    uses: ./.github/workflows/_ts-checks.yml
    secrets: inherit

  clean-wasm-artifact:
    name: Clean wasm artifact
    runs-on: ubuntu-22.04
    if: ${{ always() }}
    # dependencies should include all jobs, which interact with wasm artifact
    needs: [build-wasm-package, build-wasm-package-without-circuits, ts-checks]
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            wasm-pkg
            wasm-pkg-without-circuits
            proving-keys-pkg

  measure-gas-usage-and-verifier-code-size:
    name: Measure gas usage
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_measure-gas-and-contract-size.yml
    secrets: inherit
