---
name: PR commit

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  measure-gas-usage:
    name: Measure gas usage
    uses: ./.github/workflows/_measure-gas.yml
    secrets: inherit
