---
name: Build and add Shielder Prover Server artifacts to GitHub Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  add-ci-artifacts-to-release:
    name: Add CI artifacts to the release
    needs:
      - check-vars-and-secrets
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v7

      - name: Download enclave artifacts - EIF
        uses: ./.github/actions/download-artifact-by-run-id
        with:
          workflow-name: on-push-main.yml
          full-sha: ${{ steps.get-ref-properties.outputs.full-sha }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
          artifact-name: shielder-prover-tee-eif
          artifact-path: artifacts

      - name: Download enclave artifacts - Measurements
        uses: ./.github/actions/download-artifact-by-run-id
        with:
          workflow-name: on-push-main.yml
          full-sha: ${{ steps.get-ref-properties.outputs.full-sha }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
          artifact-name: shielder-prover-tee-measurements
          artifact-path: artifacts

      - name: Generate release artifacts checksum (SHA256)
        uses: jmgilman/actions-generate-checksum@v1
        with:
          output:
            checksums.txt
          patterns: |
            artifacts/*

      - name: Add CI artifacts to the release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            checksums.txt
            artifacts/*
