---
name: Test Download Artifact by Run ID

on:
  push:
    branches:
      - prover-server-ci

jobs: 
  main:
    name: Test Download Artifact by Run ID
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Call action get-ref-properties
        id: get-ref-properties
        uses: Cardinal-Cryptography/github-actions/get-ref-properties@v7
        with:
          ref: '2aeb66b9df73d9b81e0e430bf0a9649049f16592'

      - name: Download enclave artifacts - EIF
        uses: ./.github/actions/download-artifact-by-run-id
        with:
          workflow-name: on-push-main.yml
          full-sha: ${{ steps.get-ref-properties.outputs.full-sha }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
          artifact-name: shielder-prover-tee-eif
          artifact-path: artifacts

      - name: Download enclave artifacts - Measurements
        uses: ./.github/actions/download-artifact-by-run-id
        with:
          workflow-name: on-push-main.yml
          full-sha: ${{ steps.get-ref-properties.outputs.full-sha }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
          artifact-name: shielder-prover-tee-measurements
          artifact-path: artifacts
